language: python
python:
- "3.6"
cache:
  bundler: true
  - pip
  directories:
  - node_modules
sudo: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-numpy
install:
  - npm install -g gitbook-cli
  - pip install -r requirements.txt
env:
  global:
    secure: "WOqlWFcEaFJdoki7XUELuEEmIHV3pXmhVx5VmGGFk0m1ySdzcMvMHcgZTL4yLIZ2W/4GWwAHxrs0cWBdGRH22a26hzkxrWPoKSQAMypv05uk5H0mVuD84PQvQ16Ld2ZW8VKL8z4LYF2KXuhgD6BfAMaVxMVbsJD60hhJzO2GvL/ILF4756RrvkkH8ngILlGehCWwWHGS/5qWueO1JIGyJdqTP92w3Pk2vE8inVzWGWiNheVudKIgk6tNag6+/BnDwuZ/dKrOKS10aXCmjLRboXDin+Ifpy5qXsoNES6AdVcAgodfgoBpJQWBbH1h3q38fYW2/2/S0Of0VRnLvVshbVEz1YMr1nM8hwM+5EvIxvvPw7vM6pAw3AVRyIIp6ZQiKyM0MrWsG1xCkLf3DKLJrV7ugVOHLgAaxilVW9dyixqiWMPdmhoYiijPkdC0yHYJhJX4LaXPsgYMyAfCsa8vsxnQrb3ZWSCgzt83gIxWthGkl0aihZXvcwEecuxIl7OgpYU5/OvvuOUBu8997KZhPciJRjwcrS2hcaExXRcM6dfO31ZJXj5fI68jAhENOv0eKys6dgQe9fZQryjQJs4DfprICpSUH3mVD03nakngmzuWhpVXtIX+svwug1pMceiS+UoIDzzlQGhvNKxDlSbEwuMw6a9ujX7j4t76qZ+k7XU="
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
